### PR TITLE
Avoid relying on implicitly-defined setgroups

### PR DESCRIPTION
**Pull request by susnux**
Fix potential build errors.

This patch is from the openSUSE project (still used there).

### CODE REVIEW

**Comment by ThomasHabets** [comment]
Thanks!

**Comment by ThomasHabets** [comment]
Hang on, this isn't right. `grp.h` is already included. I'm backing this out.

**Comment by ThomasHabets** [comment]
I went in to clean up and make sure autoconf looked for `grp.h` and conditionally include it, just like the logic for the the other header files. Turns out it already was.

What makes you say this PR was needed?

**Comment by susnux** [comment]
Oh sorry, seems to be unneeded now.
This patch is used for quite a long time, tested the build success with the latest release (which is fine), but did not noticed it is fixed already without this patch.

**Comment by ThomasHabets** [comment]
Ah, alright. Are you the maintainer at opensuse that would be the one to remove it from there, or should I leave a comment [here](https://build.opensuse.org/package/show/openSUSE%3AFactory/arping2), or somewhere?

For reference this was [fixed](https://github.com/ThomasHabets/arping/commit/ba23130b) back in arping-2.16 (2015).

Thanks for working to upstream fixes. It wasn't needed this time, but it's valuable work!

**Comment by susnux** [comment]
> Are you the maintainer at opensuse that would be the one to remove it from there, or should I leave a comment [here](https://build.opensuse.org/package/show/openSUSE%3AFactory/arping2), or somewhere?

No I am not, but I already filed a submit request, for dropping that patch and updating the package:
https://build.opensuse.org/request/show/905353

> Thanks for working to upstream fixes. It wasn't needed this time, but it's valuable work!

I often see quite old patches not upstreamed (but still needed), so I decided to report them upstream, this time my testing was insufficient :/

**Pull request merged**
